Index: Makefile
===================================================================
--- a/Makefile
+++ b/Makefile
@@ -5,15 +5,15 @@ LUACPATH ?= /usr/lib/lua/5.1
 # Compile with build-in LuaSocket's help files.
 # Comment this lines if you will link with non-internal LuaSocket's help files
 #  and edit INCDIR and LIBDIR properly.
-EXTRA = luasocket
-DEFS  = -DWITH_LUASOCKET
+#EXTRA = luasocket
+#DEFS  = -DWITH_LUASOCKET
 
 # Edit the lines below to inform new path, if necessary.
 # Path below points to internal LuaSocket's help files.
 INC_PATH ?= -I/usr/include
 LIB_PATH ?= -L/usr/lib
-INCDIR    = -I. $(INC_PATH)
-LIBDIR    = -L./luasocket $(LIB_PATH)
+INCDIR    = $(INC_PATH)
+LIBDIR    = $(LIB_PATH)
 
 # For Mac OS X: set the system version
 MACOSX_VERSION=10.11
